# 目次
- Numpyとは？
    - なぜNumpyが必要？
    - Numpyの特徴とは？
    - ndarrayオブジェクト
    - Numpyを使う際の注意点
- 実際に使ってみる
    - インポートする
    - 簡単な演算
    - ndarrayの生成関数
        - np.array, np.asarray
        - np.arange
        - np.ones, np.ones_like
        - np.zeros, np.zeros_like
        - np.linspace
    - np.linalg
    - np.random
    - np.fft

# Numpyとは？
**Numpy**は、標準の演算が遅いというPythonの欠点を補うために開発された高速なベクトル演算をサポートするライブラリです。  
Pythonで科学技術計算をする上では必須と言っても良いライブラリです。  
（本稿の大部分は、「[Pythonによるデータ分析入門](https://www.oreilly.co.jp/books/9784873116556/)（O'REILLY）」の第４章を参考にして書かれています。  
この本は翻訳もわかりやすく、とても読みやすい本なのでおすすめです。）
## なぜNumpyが必要？
C言語やFortranのような**静的型付け言語（コンパイル時に型を決定する言語）**では、配列や変数を宣言する際、型を明示的にコンパイラに伝えます。  
このようにコンパイルの段階で型が決まっていると、マシンとしては余計な動作をする必要が無いために効率よくメモリを使用できる上に高速に動作します。  
一方、Pythonのような**動的型付け言語（実行時に型を決める言語）**では、そのような高速な動作を失う代わりに、型を気にせずにリストに入れたり、宣言の手間が省けたりと、柔軟で短いコードが書けるようになります。  
しかし、科学技術計算においては動作の遅さは致命的になります。  
もしPythonで科学技術計算しようとするならば、高速な動作が必要になるところでは型を指定して高速な計算ができるようにする必要があります。  
そこで生まれたのが**Numpy**です（Numerical Pythonの略）。  
Numpyでは、C言語の配列をPythonで扱いやすいオブジェクト（ndarray）として使うことで、**高速でありながら柔軟なプログラミング**が可能です。  
また、CやFortranと同様に大規模配列を扱うことにも長けているため、使いこなせればかなり強力なツールです。  
Numpyは非常に高機能であり、全ての機能を1ページで説明することは難しいです。  
本稿では、詳しい実装には立ち入らず、とりあえず使えるようになることを目的としています。
## Numpyの特徴とは？
ざっとNumpyの特徴を上げてみると、
- ベクトル演算をベースにした省メモリで高速な多次元配列（ndarrayオブジェクト）
- 行列演算（逆行列など）や乱数生成、フーリエ変換を簡単にできる
- C, C++, Fortranとの連携
- バイナリやテキストでのファイル入出力を簡単にできる

のようなものがあります。  
行列演算などの実装はCやFortranで使われているライブラリを使用しており、同等の速度を発揮します。  
## ndarrayオブジェクト
Numpyで配列と言うとき、たいていndarray（N-dimensional array）オブジェクトのことを指します。  
ndarrayはCの配列に加え、その形状や型、関数などを情報として持っています。  
本稿でも、特に断らない限り、配列はndarrayのことを意味することにします。
## Numpyを使う際の注意点
Numpyも万能ではなく、得意ではない処理もあります。それは、配列要素ごとに回すforループです。  
要素ごとにforループを回すと、Pythonの遅さが如実に出てしまい、Numpyの利点が活かせません。  
Numpyが本当に力を発揮するのは**ベクトル演算**であり、それは並列化によって実現されています。  
もし、要素ごとの計算をしたい場合は、
- CやFortranでその部分だけを書き、それをPythonで呼び出す
- NumbaやCythonといった他のライブラリを使用しコンパイルを行う

と言った方法があります。  
まずはなるべくベクトル化を試みて、それが難しい場合は上記のような手段を考えてみると良いでしょう。  

# 実際に使ってみる
## インポートする

In [16]:
import numpy as np    #慣習でnpと名付けることが多い

インポートに失敗する場合、numpyがそもそもインストールされていない可能性があります。その場合以下のようなコマンドを実行してください。  
- Anacondaの場合「conda install numpy」
- pipの場合「pip install numpy」

condaはコンパイル済みのものをインストールするためにインストールエラーが起きにくいです。  
pipはインストール時にコンパイルするため、コンパイルエラーが起きる場合があります。  

## ndarrayの構造

さっそく、一次元配列を作ってみましょう。np.array関数にリストやタプルを渡すことで作ることが出来ます。  

In [38]:
x = np.array([1., 0.01, 0.7])
print("x = {}".format(x))
print("type = {}".format(type(x)))
print("shape = {}".format(x.shape))
print("dtype = {}".format(x.dtype))
print("ndim = {}".format(x.ndim))

x = [ 1.    0.01  0.7 ]
type = <class 'numpy.ndarray'>
shape = (3,)
dtype = float64
ndim = 1


ndarrayの重要な属性として、**shape**、**dtype**があります。  
**shape**は、まさに配列の形状で、多次元配列であれば、軸に沿った要素の個数をそれぞれの軸について並べたタプルです。一次元であれば、(n,)のようなタプルになります。タプルの要素が一つしか含まれない場合、(n)とすると単なるnになってしまうので、(n,)のようにカンマを付ける必要があります。  
**dtype**は、配列の型を表すものです（floatやint、complexなど）。  
**ndim**は、配列の次元を表します。 上の場合、１次元配列なのでndim=1です。   
**type()**はPythonの組み込み関数で、何のオブジェクトかを教えてくれます（dtypeとは違うものなので注意）。  
いくつか例を挙げましょう。

In [49]:
def show_ndarray_info(x):
    x = np.asarray(x)
    print("x = {}".format(x))
    print("type = {}".format(type(x)))
    print("shape = {}".format(x.shape))
    print("dtype = {}".format(x.dtype))
    print("ndim = {}".format(x.ndim))
    print()
    
print("[整数のみを入れた場合]")
show_ndarray_info([1, 2, 3])
print("[２次元配列]")
show_ndarray_info([
        [1., 0.1, 3.],
        [3., 20., 0.07]
        ])
print("[複素数を入れた場合]")
show_ndarray_info([1j, 3+6j, 9.])

[整数のみを入れた場合]
x = [1 2 3]
type = <class 'numpy.ndarray'>
shape = (3,)
dtype = int32
ndim = 1

[２次元配列]
x = [[  1.     0.1    3.  ]
 [  3.    20.     0.07]]
type = <class 'numpy.ndarray'>
shape = (2, 3)
dtype = float64
ndim = 2

[複素数を入れた場合]
x = [ 0.+1.j  3.+6.j  9.+0.j]
type = <class 'numpy.ndarray'>
shape = (3,)
dtype = complex128
ndim = 1



### 要素へのアクセス
また、各要素にアクセスするためには、リストやタプルのようにインデックスを指定します。  
多次元配列でのアクセスは、リストなどと違う記法なので注意してください。

In [73]:
x = np.array([1., 2., 3.,])
x[0] # ==> 1.0

#スライスも使える（小さいndarrayが返ってくる）
x[1:] # ==> [ 2.,  3.]

# 多次元配列の場合
x = np.arange(20).reshape(4,5)
# ==> [[ 0,  1,  2,  3,  4],
#          [ 5,  6,  7,  8,  9],
#          [10, 11, 12, 13, 14],
#          [15, 16, 17, 18, 19]]
# まず0~19までの一次元配列を作り、そのshapeを変更して４×５の多次元配列を作っている。

x[0,1] #==> 1
x[1,-1] #==> 9 （負のインデックスは後ろから数えたもの。x[1,3]と等価）

x[3]  # １次元配列を取り出す
# ==> [15, 16, 17, 18, 19]

# #一つの軸でのスライスではndimは変わらず、shapeだけが小さくなる（２×５の多次元配列に）。
# x[2:4] 
# # ==> [[10, 11, 12, 13, 14],
# #          [15, 16, 17, 18, 19]]

# #複数の軸でのスライスも可能。
# x[2:4, 2:4]  # ２×２
# # ==> [[12, 13],
# #          [17, 18]]

array([15, 16, 17, 18, 19])

## 簡単な演算
スカラーとの四則演算は普通のベクトルのような書き方ができます（Fortranと一緒）。  
このような演算はリストやタプルでは出来ないので、そのためにndarrayに変換することもよくあります。

In [26]:
x = np.array([1., 0.01, 0.7])
x + 1 # ==> [ 2.  ,  1.01,  1.7 ]
2 * x # ==> [ 2.  ,  0.02,  1.4 ]
x / 1e5 # ==> [  1.00000000e-05,   1.00000000e-07,   7.00000000e-06]

array([  1.00000000e-05,   1.00000000e-07,   7.00000000e-06])

同じ形状の配列同士の四則演算は、要素ごとに演算した結果になります。  
（異なる形状の配列であっても、場合によっては演算できることがあり、それを**ブロードキャスト**と言います（後述））

In [30]:
x = np.array([8., 0.3, 90])
y = np.array([4., 0.2, 150])
x + y # ==> [  12. ,    0.5,  240. ]
x - y # ==> [  4. ,   0.1, -60. ]
x * y # ==> [  3.20000000e+01,   6.00000000e-02,   1.35000000e+04]
x / y # ==> [ 2. ,  1.5,  0.6]

array([ 2. ,  1.5,  0.6])

多次元配列でも同じように要素ごとの演算になります。  
行列演算がしたい場合は、np.dot関数を用いるか、Python3.5以降であれば@マークを使えます。

In [78]:
# ３×３行列を作成
A = np.arange(9).reshape(3,3)
# ==> [[0, 1, 2],
#          [3, 4, 5],
#          [6, 7, 8]]

# ３×３の単位行列の２倍
B = np.eye(3) * 2
# ==> [[ 2.,  0.,  0.],
#          [ 0.,  2.,  0.],
#          [ 0.,  0.,  2.]]

# 要素ごとの積になる
A * B
# ==> [[  0.,   0.,   0.],
#          [  0.,   8.,   0.],
#          [  0.,   0.,  16.]]

# 行列積
np.dot(A, B)
# ==> [[  0.,   2.,   4.],
#          [  6.,   8.,  10.],        2*Aと等しくなっている
#          [ 12.,  14.,  16.]]

# Python3.5以降であれば、行列積を@で記述可
A @ B
# ==> [[  0.,   2.,   4.],
#          [  6.,   8.,  10.],
#          [ 12.,  14.,  16.]]

array([[  0.,   2.,   4.],
       [  6.,   8.,  10.],
       [ 12.,  14.,  16.]])

## ndarrayの生成関数
色々な配列を作る便利な関数が用意されています。ここではそれらを紹介します。
### np.array, np.asarray
上でも述べた関数です。リストやタプルを引数に取り、配列を返す関数です。  
型は指定しない場合は、勝手に推測してくれますが、キーワード引数で指定することも出来ます。
np.asarrayは引数がndarrayであれば、そのままndarrayを返し、そうでないならnp.arrayと同じ働きをする関数です。

In [81]:
# dtypeを指定
np.array([1, 2, 3], dtype=float).dtype # ==> dtype('float64')

#指定しない場合は推測してくれる
np.array([1, 2, 3]).dtype # ==> dtype('int32')

dtype('int32')

### np.arange
Python組み込み関数のrange()と同じ働きをする関数で、ndarrayを返します。



In [102]:
# 引数が一つの場合
np.arange(10) # ==> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
np.arange(10.) # ==> [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]
np.arange(10, dtype=float) # ==> [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]

# 引数が２つの場合、startとstopになる（stopは含まない）
np.arange(3, 10) # ==> [3, 4, 5, 6, 7, 8, 9]

#引数が３つの場合、start, stop, stepになる
np.arange(0, 1, 0.1) # ==> [ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9]
np.arange(start=0, stop=1, step=0.1) #上と等価

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

### np.ones, np.ones_like
np.onesは、引数で与えられたshapeで、全ての要素が１であるようなndarrayを返します。  
np.ones_likeは、引数にndarrayを取り、そのndarrayのshapeと同じshapeで全ての要素が１となるndarrayを返します。

In [112]:
#１次元の場合はスカラーを引数に与えることが可能
np.ones(5) # ==> [ 1.,  1.,  1.,  1.,  1.]
# np.ones((5,))と等価

# 多次元配列の場合、タプルを引数にしなければならない（2×２×２行列）
np.ones((2,2,2))
# ==> [[[ 1.,  1.],
#           [ 1.,  1.]],
#
#          [[ 1.,  1.],
#           [ 1.,  1.]]]

#デフォルトではfloatなので、dtypeをintにしてみる
np.ones(5, dtype=int) # ==> [1, 1, 1, 1, 1]

A = np.arange(10).reshape(2,5)
A.shape # ==> (2, 5)
np.ones_like(A)
# ==> [[1, 1, 1, 1, 1],
#          [1, 1, 1, 1, 1]]

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### np.zeros, np.zeros_like
全ての要素を0にする他は、np.ones, np.ones_likeと同じなのでそちらを見てください。

### np.empty, np.empty_like
上の２つと似ていますが、こちらは初期化をせずに配列の領域だけを確保する関数です。  
巨大な配列を自分で初期化したい場合や、値は何でもいいが配列だけ作りたいときに使います。   
初期化のプロセスを省略するためにnp.zerosなどよりも高速に動作します。  
ときどき変な値が入ってることがあるので、自分で初期化するときのみ使うのが吉です。

In [263]:
# 2048個のbool型の中にあるTrueの個数（実行するたびに変化する）
np.empty(2048, dtype=np.bool).sum()

1196

### np.linspace
start, stopの２つを引数に取り、startからendまで均等に分けた配列を返します。  
キーワード引数としてnumがあり、均等に分ける個数を指定できます。デフォルトではnum=50です。  

> np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

endpointはstopを含むかどうかをBooleanで渡す引数です。

In [268]:
np.linspace(0, 1)

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

In [272]:
#この２つは等価
np.linspace(0, np.pi, 10)
np.linspace(0, np.pi, num=10)

array([ 0.        ,  0.34906585,  0.6981317 ,  1.04719755,  1.3962634 ,
        1.74532925,  2.0943951 ,  2.44346095,  2.7925268 ,  3.14159265])

In [274]:
#endpoint=Falseの場合。stopの値を含まない。
np.linspace(0, np.pi, 10, endpoint=False)

array([ 0.        ,  0.31415927,  0.62831853,  0.9424778 ,  1.25663706,
        1.57079633,  1.88495559,  2.19911486,  2.51327412,  2.82743339])