# 目次
- [インデックス参照](#インデックス参照)
    - [スライス](#スライス)
    - [ファンシーインデックス参照](#ファンシーインデックス参照)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## インデックス参照
Numpyでは、部分配列の取り出し方に様々な種類があり、使いこなせると便利です。  

ただ、取り出し方が**コピー**であるか**ビュー（参照）**であるかを混乱することがあるので、チェックしておいてください。  
### スライス
Pythonのリストやタプルにも実装されているスライスをndarrayに対してするとその部分配列が**ビュー（参照）**で返ってきます。  
つまり、その取り出した部分配列を書き換えると元々の配列も変わるということです。  
スライスは高速に動作するので、使えるときはガンガン使っていきましょう。  
一例を見てみます。

In [2]:
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# スライスした部分配列（行1, 2）の要素に全て-1を代入する
arr[1:3] = 0

# オリジナルの配列
arr

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15]])

In [4]:
# 全て0に初期化（配列を再生成せず、要素のみ書き換えている）
arr[:]  = 0
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

使い道としては、各軸の値をなんらかの計算をしたあと、再び代入するのに使います。

In [5]:
# 一様乱数
arr = np.random.rand(3, 4)
arr

array([[0.86830027, 0.19571313, 0.77775386, 0.05897186],
       [0.94106792, 0.0309926 , 0.43908545, 0.30118229],
       [0.54388156, 0.03884835, 0.55800978, 0.72663719]])

In [6]:
# ３行目を書き換える
arr[2] = arr[2] - 1
arr

array([[ 0.86830027,  0.19571313,  0.77775386,  0.05897186],
       [ 0.94106792,  0.0309926 ,  0.43908545,  0.30118229],
       [-0.45611844, -0.96115165, -0.44199022, -0.27336281]])

In [7]:
# ２列めを書き換える
arr[:, 1] = arr[:, 1] + arr[:, 2]
arr

array([[ 0.86830027,  0.97346699,  0.77775386,  0.05897186],
       [ 0.94106792,  0.47007805,  0.43908545,  0.30118229],
       [-0.45611844, -1.40314188, -0.44199022, -0.27336281]])

オリジナルの配列が変わってほしくないときは、copy関数で同じ配列を複製できます。

In [8]:
arr_copied = arr.copy()
arr_copied

array([[ 0.86830027,  0.97346699,  0.77775386,  0.05897186],
       [ 0.94106792,  0.47007805,  0.43908545,  0.30118229],
       [-0.45611844, -1.40314188, -0.44199022, -0.27336281]])

#### 代入時の注意点
配列に値や配列を代入するときには、意識的にスライスを使うようにした方がいいです。  
例えばスカラーを配列の全要素に代入しようとしたとき、スライスを使わないといけません。

In [9]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# ↓-100をaの全要素に代入するつもりで書いたら
# 配列ですらなくなっている！？
a = -100
a

-100

In [11]:
# 正しくは
a = np.arange(10)
a[:] = -100
a

array([-100, -100, -100, -100, -100, -100, -100, -100, -100, -100])

配列として扱いたい場合は、スライスを使った代入を心がけましょう。

### ファンシーインデックス参照
スライスよりも柔軟に部分配列を取り出せるインデックス参照が**ファンシーインデックス参照**です。  
配列（ndarrayやリスト、タプルなど）をインデックスに入れると、部分配列（コピー）を返すという機能です。  
Numpyの使いやすさを格段に上げる機能であり、使う機会も多くなると思います。　　  
インデックスに配列を入れることで、対応する軸を抜き出すということをしてくれます。

In [12]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
# ファンシーインデックス参照の一例（行1, 3を抜き出す）
a[[1, 3]]

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [14]:
# ファンシーインデックス参照の一例（列0, 1を抜き出す）
a[:, [0, 1]]

array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [15]:
# ファンシーインデックス参照を使った代入の例（列0, 1をそれぞれ10倍する）
a[:, [0, 1]] = a[:, [0, 1]] * 10
a

array([[  0,  10,   2],
       [ 30,  40,   5],
       [ 60,  70,   8],
       [ 90, 100,  11]])

ファンシーインデックス参照は直接代入するときは上のようにビューとして振る舞いますが、変数に格納するときはコピーされます。

In [16]:
a

array([[  0,  10,   2],
       [ 30,  40,   5],
       [ 60,  70,   8],
       [ 90, 100,  11]])

In [17]:
# 列0, 1を抜き出す（コピーになる）
b = a[:, [0, 1]]
b

array([[  0,  10],
       [ 30,  40],
       [ 60,  70],
       [ 90, 100]])

In [18]:
# 全要素を0
b[:] = 0
b

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [19]:
# もともとの配列は書き換わらない（コピーされている！）
a

array([[  0,  10,   2],
       [ 30,  40,   5],
       [ 60,  70,   8],
       [ 90, 100,  11]])